### ISSUE TITLE
Мой отчет о результатах коммита

### ISSUE THREAD

**Issue by UMSF-K13-2-Asmolova** [UMSF-K13-2-Asmolova/AnnaGit#1]
Я выполнила поставленную задачу и дала права collaboration пользователю honia19. 
Получила опыт пуша файлов контроля версий GitHub 
[Документ Microsoft Word.docx](https://github.com/UMSF-K13-2-Asmolova/AnnaGit/files/289661/Microsoft.Word.docx)

**Comment by Smoktii** [comment]
ок4
